version: "3.8"

networks:
    kafka-net:
        driver: bridge
    backend-net:
        driver: bridge
    shared-net:
        driver: bridge

volumes:
    data01:
        driver: local

services:
    zookeeper-server:
        image: zookeeper:latest
        networks:
            - kafka-net
        ports:
            - 2181:2181
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

    kafka-server:
        image: apache/kafka:latest
        networks:
            - kafka-net
            - shared-net
        ports:
            - 9092:9092
        environment:
            - KAFKA_NODE_ID=1
            - KAFKA_PROCESS_ROLES=broker,controller
            - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
        depends_on:
            - zookeeper-server

    elasticsearch-server:
        image: elasticsearch:8.11.3
        networks:
            - backend-net
            - shared-net
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - discovery.type=single-node
        volumes:
            - data01:/usr/share/elasticsearch/data

    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        container_name: kafka-ui
        ports:
            - 8080:8080
        environment:
            - KAFKA_CLUSTERS_0_NAME=local
            - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-server:9092
            - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper-server:2181
        networks:
            - kafka-net
            - shared-net
        depends_on:
            - kafka-server
            - zookeeper-server

