version: "3.7"

networks:
    kafka-net:
        driver: bridge
    backend-net:
        driver: bridge

volumes:
    data01:
        driver: local

services:
    zookeeper-server:
        image: bitnami/zookeeper:latest
        networks:
            - kafka-net
        ports:
            - 2181:2181
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

    kafka-server:
        image: bitnami/kafka:latest
        networks:
            - kafka-net
        ports:
            - 9092:9092
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper-server

    elasticsearch-server:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
        networks:
            - backend-net
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - discovery.type=single-node
        volumes:
            - data01:/usr/share/elasticsearch/data

    orchestrator:
        image: orchestrator-server:latest
        networks:
            - backend-net
        ports:
            - 1200:1200
        working_dir: /app
        volumes:
            - ./:/app
            - ~/.ssh:/root/.ssh
        depends_on:
            - elasticsearch-server
